# Generated by Django 5.2 on 2025-04-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_employment_type_alter_job_experience_level_and_more'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('skills_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('overall_cv_score', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
