# Generated by Django 5.2 on 2025-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_cvscoresummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parse_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
    ]
