# Generated by Django 5.2 on 2025-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_parsedresumedata_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
