# Generated by Django 5.2 on 2025-04-21 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('work_mode', models.CharField(blank=True, choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=10, null=True)),
                ('salary_type', models.CharField(blank=True, choices=[('ONSITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=10, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior')], max_length=10, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FULLTIME', 'Full-time'), ('PARTTIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], max_length=10, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
