# Generated by Django 5.2 on 2025-04-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_salary_type_jobinterviewconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('range', 'Range')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=10, null=True),
        ),
    ]
