# Generated by Django 5.2 on 2025-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
