# Generated by Django 5.2 on 2025-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='share_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
