# Generated by Django 5.2 on 2025-04-21 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('ai', 'AI'), ('inperson', 'In-person')], default='ai', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('scored', 'Scored'), ('reviewed', 'Reviewed')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=15, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], default='pending', max_length=15)),
                ('expected_answer', models.TextField(blank=True, null=True)),
                ('scoring_guideline', models.TextField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=[])),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('score_override', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='interviews/interview-questions/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('trigger_keywords', models.JSONField(blank=True, default=[])),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('score_threshold', models.FloatField(blank=True, null=True)),
                ('follow_up_to_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewquestion')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interview')),
                ('triggered_by_answer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewanswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interviewquestion'),
        ),
        migrations.CreateModel(
            name='InterviewScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('challenge_score', models.FloatField(blank=True, null=True)),
                ('appearance_score', models.FloatField(blank=True, null=True)),
                ('facial_score', models.FloatField(blank=True, null=True)),
                ('body_language_score', models.FloatField(blank=True, null=True)),
                ('environment_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary_feedback', models.TextField(blank=True)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('rejoined', 'Rejoined'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='waiting', max_length=15)),
                ('is_reconnect', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
