# Generated by Django 5.2 on 2025-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interview_interview_type_alter_interview_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanswer',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='trigger_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
