# Generated by Django 5.2 on 2025-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewanswer_ai_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='share_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
