# Generated by Django 5.2 on 2025-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_share_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanswer',
            name='media_url',
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='interviews/interview-answers/'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], default='video', max_length=15, null=True),
        ),
    ]
