# Generated by Django 5.2 on 2025-04-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('parse_resume', 'Parse Resume'), ('generate_question', 'Generate Question')], max_length=50)),
                ('system_message', models.TextField(blank=True, help_text='Optional system prompt to set assistant behavior')),
                ('template', models.TextField(help_text='Jinja2 or plain-text prompt with variables like {{ resume_text }}')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
