# Generated by Django 5.2 on 2025-04-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('parse_resume', 'Parse Resume'), ('parse_resume_sections', 'Parse Resume Sections'), ('scoring_resume_job', 'Scoring Resume Job')], max_length=50),
        ),
    ]
