# Generated by Django 5.2 on 2025-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0002_alter_prompt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('parse_resume', 'Parse Resume'), ('parse_resume_sections', 'Parse Resume Sections'), ('scoring_resume_job', 'Scoring Resume Job'), ('generate_questions', 'Generate Interview Questions')], max_length=50),
        ),
    ]
